package org.firstinspires.ftc.teamcode.pedroPathing.autonomous;

public enum AutonomousStateEnum {

    //PRELOAD STATES
    DRIVE_FROM_START_TO_LAUNCH,
    SHOOT_PRELOAD,

    //NEAREST ARTIFACT GROUP
    DRIVE_FROM_LAUNCH_TO_NEAR_ARTIFACT_GROUP,
    DRIVE_FROM_NEAR_ARTIFACT_GROUP_TO_LAUNCH,
    INTAKE_NEAR_ARTIFACT_GROUP,
    SHOOT_NEAR_ARTIFACT_GROUP,

    //MIDDLE ARTIFACT GROUP
    DRIVE_FROM_LAUNCH_TO_MIDDLE_ARTIFACT_GROUP,
    DRIVE_FROM_MIDDLE_ARTIFACT_GROUP_TO_LAUNCH,
    INTAKE_MIDDLE_ARTIFACT_GROUP,
    SHOOT_MIDDLE_ARTIFACT_GROUP,

    //FAR ARTIFACT_GROUP
    DRIVE_FROM_LAUNCH_TO_FAR_ARTIFACT_GROUP,
    DRIVE_FROM_FAR_ARTIFACT_GROUP_TO_LAUNCH,
    INTAKE_FAR_ARTIFACT_GROUP,
    SHOOT_FAR_ARTIFACT_GROUP,

    //LOADING ZONE ARTIFACT_GROUP
    DRIVE_FROM_LAUNCH_TO_LOADING_ZONE_ARTIFACT_GROUP,
    DRIVE_FROM_LOADING_ZONE_ARTIFACT_GROUP_TO_LAUNCH,
    INTAKE_LOADING_ZONE_ARTIFACT_GROUP,
    SHOOT_LOADING_ZONE_ARTIFACT_GROUP,

    //END GAME
    DRIVE_FROM_LAUNCH_TO_END,
    END_STATE
}
