package org.firstinspires.ftc.teamcode.pedroPathing.enums;

public enum AutonomousStateEnum {

    //PRELOAD_ARTIFACT_GROUP
    DRIVE_FROM_START_TO_LAUNCH,
    SHOOT_PRELOAD,

    //ARTIFACT_GROUP_1
    DRIVE_FROM_LAUNCH_TO_ARTIFACT_GROUP_1,
    DRIVE_FROM_ARTIFACT_GROUP_1_TO_LAUNCH,
    INTAKE_ARTIFACT_GROUP_1,
    SHOOT_ARTIFACT_GROUP_1,

    //ARTIFACT_GROUP_2
    DRIVE_FROM_LAUNCH_TO_ARTIFACT_GROUP_2,
    DRIVE_FROM_ARTIFACT_GROUP_2_TO_LAUNCH,
    INTAKE_ARTIFACT_GROUP_2,
    SHOOT_ARTIFACT_GROUP_2,

    //ARTIFACT_GROUP_3
    DRIVE_FROM_LAUNCH_TO_ARTIFACT_GROUP_3,
    DRIVE_FROM_ARTIFACT_GROUP_3_TO_LAUNCH,
    INTAKE_ARTIFACT_GROUP_3,
    SHOOT_ARTIFACT_GROUP_3,

    //ARTIFACT_GROUP_4
    DRIVE_FROM_LAUNCH_TO_ARTIFACT_GROUP_4,
    DRIVE_FROM_ARTIFACT_GROUP_4_TO_LAUNCH,
    INTAKE_ARTIFACT_GROUP_4,
    SHOOT_ARTIFACT_GROUP_4,

    //END GAME
    ABORT,
    DRIVE_FROM_LAUNCH_TO_END,
    ENDING_STATE,
    COMPLETE
}